// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/areaType": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "添加面积分类",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.AreaTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/areaType/{ids}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "删除面积分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "面积分类ID 多个用,分开",
                        "name": "ids",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/areaType/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "修改面积分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "面积分类ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.AreaTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/department": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "添加部门",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.DepartmentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/industry": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "添加经营业态",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.IndustryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/industry/{ids}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "删除经营业态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "租金分类ID 多个用,分开",
                        "name": "ids",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/industry/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "修改经营业态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "经营业态ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.IndustryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/post": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "添加岗位",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.PostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/rentType": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "添加租金分类",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.RentTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/rentType/{ids}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "删除租金分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "租金分类ID 多个用,分开",
                        "name": "ids",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/rentType/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "修改租金分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "租金分类ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.RentTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/role": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "添加角色",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.RoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/storeType": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "添加店铺类型",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.StoreTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/storeType/{ids}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "删除店铺类型",
                "parameters": [
                    {
                        "type": "string",
                        "description": "租金分类ID 多个用,分开",
                        "name": "ids",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/storeType/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台"
                ],
                "summary": "修改店铺类型",
                "parameters": [
                    {
                        "type": "string",
                        "description": "经营业态ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.StoreTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/areatype": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础数据"
                ],
                "summary": "查询面积分类",
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/city": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础数据"
                ],
                "summary": "根据省代码获取城市",
                "parameters": [
                    {
                        "type": "string",
                        "description": "省代码",
                        "name": "province_code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/district": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础数据"
                ],
                "summary": "根据城市代码获取区",
                "parameters": [
                    {
                        "type": "string",
                        "description": "城市代码",
                        "name": "city_code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/districts": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础数据"
                ],
                "summary": "获取所有区",
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/enableIndustry": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础数据"
                ],
                "summary": "查询已启用行业类型",
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/enableStoreType": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础数据"
                ],
                "summary": "查询已启用店铺类型",
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/industry": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础数据"
                ],
                "summary": "查询行业类型",
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/industryParent": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础数据"
                ],
                "summary": "查询已启用最上级行业",
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/province": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础数据"
                ],
                "summary": "获取省",
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/renttype": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础数据"
                ],
                "summary": "查询租金分类",
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/storeType": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础数据"
                ],
                "summary": "查询店铺类型",
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/street": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础数据"
                ],
                "summary": "根据区代码获取街道",
                "parameters": [
                    {
                        "type": "string",
                        "description": "区代码",
                        "name": "district_code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/common/verificationcode": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "公共接口"
                ],
                "summary": "获取验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号码",
                        "name": "tel",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/propertyInfo": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "物业信息"
                ],
                "summary": "根据条件获取物业信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "行业ID",
                        "name": "industry_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "店铺类型ID",
                        "name": "store_type_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "省代码",
                        "name": "province_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "城市代码",
                        "name": "city_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "区代码",
                        "name": "district_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "街道代码",
                        "name": "street_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "面积范围ID",
                        "name": "area_type_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "租金范围ID",
                        "name": "rent_type_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "最小面积",
                        "name": "min_area",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "最大面积",
                        "name": "max_area",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "最小租金",
                        "name": "min_rent",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "最大租金",
                        "name": "max_rent",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "模型类型 0-转让 ｜ 1-出售 ｜ 3-出租 | 4-求租 ｜ 5-求购",
                        "name": "model_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "业务类型 0-商铺 ｜ 1-写字楼 ｜ 2-厂房仓库",
                        "name": "bus_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序 area-面积 ｜ rent-租金 ｜ created_at-发布时间（默认）",
                        "name": "sort_condition",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "页大小 （默认30）",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "跳转页码",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/propertyInfo/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "物业信息"
                ],
                "summary": "查看物业详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "物业信息ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "查看用户信息",
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "修改用户信息",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.EditUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/user/edituserpass": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "修改用户密码",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.EditUserPass"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/user/findStore": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "修改我要找铺信息",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UserFindStoreRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "我要找铺",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UserFindStoreRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/user/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/user/propertyInfo": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "查看用户已发布物业信息",
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/user/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "注册",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UserRegister"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/user/storetransfer": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "修改店铺转让信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "经营业态ID",
                        "name": "industry_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "店铺类型",
                        "name": "store_type_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "可否空转",
                        "name": "idling",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "面积（单位：平方米）",
                        "name": "area",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "是否营业中 0-新铺 ｜ 1-空置中 ｜ 2-营业中",
                        "name": "in_operation",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "租金（单位：元/月）",
                        "name": "rent",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "转让费用（单位：万元 不录入则显示为面议）",
                        "name": "transfer_fee",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "适合经营范围id，多个用，拼接",
                        "name": "industry_ranges",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "图片",
                        "name": "image",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "标题",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "联系人",
                        "name": "nickname",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "联系手机",
                        "name": "telephone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "省代码",
                        "name": "province_code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "城市代码",
                        "name": "city_code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "区代码",
                        "name": "district_code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "街道代码",
                        "name": "street_code",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "详细地址",
                        "name": "address",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "详细描述",
                        "name": "description",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "店铺转让",
                "parameters": [
                    {
                        "type": "string",
                        "description": "经营业态ID",
                        "name": "industry_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "店铺类型",
                        "name": "store_type_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "可否空转",
                        "name": "idling",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "面积（单位：平方米）",
                        "name": "area",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "租金（单位：元/月）",
                        "name": "rent",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "转让费用（单位：万元 不录入则显示为面议）",
                        "name": "transfer_fee",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "适合经营范围id，多个用，拼接",
                        "name": "industry_ranges",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "图片",
                        "name": "image",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "标题",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "联系人",
                        "name": "nickname",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "联系手机",
                        "name": "telephone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "省代码",
                        "name": "province_code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "城市代码",
                        "name": "city_code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "区代码",
                        "name": "district_code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "街道代码",
                        "name": "street_code",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "详细地址",
                        "name": "address",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "详细描述",
                        "name": "description",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.AreaTypeRequest": {
            "type": "object",
            "properties": {
                "max_area": {
                    "description": "最大面积（单位：平方米）",
                    "type": "number"
                },
                "min_area": {
                    "description": "最小面积（单位：平方米）",
                    "type": "number"
                }
            }
        },
        "entity.DepartmentRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "enable": {
                    "description": "是否启用",
                    "type": "boolean"
                },
                "leading": {
                    "description": "负责人",
                    "type": "string"
                },
                "name": {
                    "description": "部门名称",
                    "type": "string"
                },
                "parent_id": {
                    "description": "上级ID 0为最顶级",
                    "type": "integer"
                },
                "phone": {
                    "description": "联系电话",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                }
            }
        },
        "entity.EditUser": {
            "type": "object",
            "properties": {
                "QQ": {
                    "description": "QQ",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "landlinenumber": {
                    "description": "座机号码",
                    "type": "string"
                },
                "nickname": {
                    "description": "姓名",
                    "type": "string"
                },
                "sex": {
                    "description": "性别 0:未知 ｜ 1:男 ｜ 2:女 （空或其他默认未知）",
                    "type": "string"
                },
                "telephone": {
                    "description": "手机号码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "entity.EditUserPass": {
            "type": "object",
            "properties": {
                "new_pass": {
                    "description": "新密码",
                    "type": "string"
                },
                "old_pass": {
                    "description": "旧密码",
                    "type": "string"
                }
            }
        },
        "entity.IndustryRequest": {
            "type": "object",
            "properties": {
                "is_enable": {
                    "description": "是否启用",
                    "type": "boolean"
                },
                "name": {
                    "description": "行业名称",
                    "type": "string"
                },
                "parent_id": {
                    "description": "父类型ID",
                    "type": "integer"
                },
                "sort": {
                    "description": "行业排序 越大越靠前",
                    "type": "integer"
                }
            }
        },
        "entity.PostRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "岗位编码",
                    "type": "string"
                },
                "enable": {
                    "description": "是否启用",
                    "type": "boolean"
                },
                "name": {
                    "description": "岗位名称",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                }
            }
        },
        "entity.RentTypeRequest": {
            "type": "object",
            "properties": {
                "max_rent": {
                    "description": "最高租金（单位：元/月）",
                    "type": "number"
                },
                "min_rent": {
                    "description": "最低租金（单位：元/月）",
                    "type": "number"
                }
            }
        },
        "entity.ResponseData": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回数据",
                    "type": "object",
                    "additionalProperties": true
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                },
                "status": {
                    "description": "成功失败标志；true：成功 、false：失败",
                    "type": "boolean"
                }
            }
        },
        "entity.RoleRequest": {
            "type": "object",
            "properties": {
                "enable": {
                    "description": "是否启用",
                    "type": "boolean"
                },
                "menu_powers": {
                    "description": "菜单权限",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.RoleRequestMenuPower"
                    }
                },
                "name": {
                    "description": "角色名称",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                }
            }
        },
        "entity.RoleRequestMenuPower": {
            "type": "object",
            "properties": {
                "menu_id": {
                    "description": "菜单ID",
                    "type": "integer"
                },
                "menu_title": {
                    "description": "菜单标题",
                    "type": "string"
                }
            }
        },
        "entity.StoreTypeRequest": {
            "type": "object",
            "properties": {
                "is_enable": {
                    "description": "是否启用",
                    "type": "boolean"
                },
                "name": {
                    "description": "类型名称",
                    "type": "string"
                },
                "sort": {
                    "description": "类型排序 越大越靠前",
                    "type": "integer"
                }
            }
        },
        "entity.UserFindStoreRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "详细描述",
                    "type": "string"
                },
                "industry_id": {
                    "description": "经营业态ID",
                    "type": "integer"
                },
                "lots": {
                    "description": "考虑地段",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "max_area": {
                    "description": "最大面积（单位：平方米）",
                    "type": "number"
                },
                "max_rent": {
                    "description": "最高租金（单位：元/月）",
                    "type": "number"
                },
                "min_area": {
                    "description": "最小面积（单位：平方米）",
                    "type": "number"
                },
                "min_rent": {
                    "description": "最低租金（单位：元/月）",
                    "type": "number"
                },
                "nickname": {
                    "description": "联系人",
                    "type": "string"
                },
                "store_type_id": {
                    "description": "店铺类型ID",
                    "type": "integer"
                },
                "telephone": {
                    "description": "联系手机",
                    "type": "string"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                }
            }
        },
        "entity.UserLogin": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "entity.UserRegister": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "telephone": {
                    "description": "手机号码",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
